# This file describes a Fastly Compute@Edge package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = ["Glitch"]
description = "Fastly in Glitch"
language = "javascript"
manifest_version = 2
name = "fastly-compute-starter"

[scripts]
  build = "npm run build"

[setup]

  [setup.backends]

    [setup.backends.glitch]
      address = "fastly-compute-starter.glitch.me"
      override_host = "fastly-compute-starter.glitch.me"
      description = "Glitch backend"
      port = 443
